### ISSUE TITLE
GPU specifing bug?

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#10]
I run my script and specify to use the GPUs 4,5,6,7. But InplaceABNSync is always based on [0,1,2,3], which is very strange?

As far as I am concerned, the design of your method must specify to use multi-gpus starting from  GPU0 as the worker , master design. Am I right?

There is a bug here(line#137 of bn.py), 
`
        self.devices = devices if devices else list(range(torch.cuda.device_count()))`

![default](https://user-images.githubusercontent.com/4639578/35430094-bfdbabd4-02b1-11e8-9859-8dbb57bf9a1d.png)

**Comment by ducksoup** [comment]
@PkuRainBow I see two different solutions here:
1. In case you are specifying which GPUs to use via the [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) environment variable, then the InplaceABNSync showing `[0, 1, 2, 3]` is actually expected behavior and working as intended. In fact, when using this method, from Pytorch's perspective the GPUs you mask away do not exist at all, and the remaining devices are re-numbered starting from zero.
As an example, if you set `CUDA_VISIBLE_DEVICES="0,4,6,7"`, then Pytorch sees four GPU devices, with IDs `[0,1,2,3]`, where ID 0 corresponds to the actual GPU 0, ID 1 corresponds to the actual GPU 4 and so on.
This is the same as any other CUDA program.
2. In case you are manually controlling which GPUs to use from within your program (_e.g._ by providing the `devices` argument to the constructor of `nn.DataParallel`), then you must also propagate this information to the InplaceABNSync layers, by passing the same `devices` argument to their constructor.

**NOTE**: the `network/devices` configuration parameter that can be specified in the JSON configuration files for our scripts follows the same logic as the point 1 above, _i.e._ only the GPUs visible to the script are taken into account, and the IDs start from 0.

**Comment by PkuRainBow** [comment]
![default](https://user-images.githubusercontent.com/4639578/35432155-20204bf0-02ba-11e8-81b7-1d57014e6f10.png)

**Comment by ducksoup** [comment]
@PkuRainBow I'm sorry but I don't understand what that screen-shot is supposed to show.

**Comment by PkuRainBow** [comment]
@ducksoup         if x.get_device() == self.devices[0]:

**Comment by rotabulo** [comment]
@PkuRainBow are you using CUDA_VISIBLE_DEVICES=4,5,6,7 _and_ passing `device` arguments the InPlaceABNSync ?

**Comment by PkuRainBow** [comment]
@rotabulo Yes, exactly!

**Comment by rotabulo** [comment]
@PkuRainBow Then you are probably erroneously passing 4,5,6,7 also to the `device` argument, since gpus have been already logically remapped to 0,1,2,3 by the env variable.

**Comment by ducksoup** [comment]
@PkuRainBow Passing `CUDA_VISIBLE_DEVICES=4,5,6,7` is enough to let the script use those devices, without modifying anything else.
Once you pass `CUDA_VISIBLE_DEVICES=4,5,6,7`, inside the script those GPUs get renamed as `0,1,2,3`, but they are infact _the correct GPUs_. You should be able to check this from `nvidia-smi`.

**Comment by PkuRainBow** [comment]
It seems contradict with what you have said ...

Here is the bug if I only pass the CUDA_VISIBLE_DEVICES=4,5,6,7 without setting the parameters of the InplaceABNSync...

![default](https://user-images.githubusercontent.com/4639578/35432936-ad6b71a4-02bc-11e8-802c-e95ab96ab3eb.png)

**Comment by ducksoup** [comment]
@PkuRainBow From what I can see in the error logs you posted there's nothing indicating that the errors are due to the wrong GPUs being used.

Can you please try using InplaceABN instead of InplaceABNSync and check if the error occurs?
