### ISSUE TITLE
CUDA erro: an illegal memory access was encountered

### ISSUE THREAD

**Issue by PkuRainBow** [mapillary/inplace_abn#11]
Have anyone ever meet this error?

![default](https://user-images.githubusercontent.com/4639578/35479172-a706269a-042b-11e8-9276-371adb3d1d68.png)

**Comment by pkontschieder** [comment]
@PkuRainBow it seems like your error is unrelated to the code we are providing and therefore not a qualified issue for our repository

**Comment by sbelharbi** [comment]
hi @PkuRainBow 
I am running into the same issue. Did you find a way to deal with it? thanks
```sh
File "../libs/bn.py", line 109, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
  File "../libs/functions.py", line 99, in forward
    running_mean.mul_((1 - ctx.momentum)).add_(ctx.momentum * mean)
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by PkuRainBow** [comment]
I still meet this problem.

Very strange!

```
  File "/msravcshare/yuyua/code/segmentation/openseg.pytorch/lib/extensions/inplace_abn_1/bn.py", line 119, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
  File "/msravcshare/yuyua/code/segmentation/openseg.pytorch/lib/extensions/inplace_abn_1/functions.py", line 155, in forward
    batch_size = x.new_tensor([x.shape[0]],dtype=torch.long)
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by rotabulo** [comment]
@PkuRainBow due to the asynchronous nature of operations, the error happened somewhere before in the network. You can try setting `CUDA_LAUNCH_BLOCKING=1` to serialize operations and figure out the exact point where the issue appears.

**Comment by PkuRainBow** [comment]
@rotabulo It would be great if you could help check more details in https://github.com/mapillary/inplace_abn/issues/109

**Comment by PkuRainBow** [comment]
@rotabulo Besides, I have not used the distributed training and I simply want to train my model with pytorch1.0~

**Comment by sbelharbi** [comment]
@PkuRainBow can you try running the code using `CUDA_LAUNCH_BLOCKING=1` as suggested by @rotabulo ? it will point to the place where the error occurs for the first time (what you are showing is the place of the second call).

Does your code run fine on CPU?

You can try to run the code on another device to see if the issue is device dependent or not.

See also: [link](https://discuss.pytorch.org/t/weird-cuda-illegal-memory-access-error/8848/17).

**Comment by PkuRainBow** [comment]
@sbelharbi When I set as below,

`CUDA_LAUNCH_BLOCKING=1  ${PYTHON} -u main.py  ....`

The program just output nothing and I have waited for more than 2 minutes.

I am wondering what is the exact usage of the **CUDA_LAUNCH_BLOCKING=1**.

**Comment by PkuRainBow** [comment]
@sbelharbi It would be great if could help me check the posted https://github.com/mapillary/inplace_abn/issues/109  with more details.

**Comment by sbelharbi** [comment]
> I am wondering what is the exact usage of the **CUDA_LAUNCH_BLOCKING=1**.

It forces synchronous computation on the GPU.
It is weird that there is no output when you use `CUDA_LAUNCH_BLOCKING=1`. Can you wait longer ... probably you are doing large computations ... since you are in a sequential mode, it may take long.

Can you check the size of `x` at the line where the error occurs? (print it just before that line ...) it seems that there is something wrong with the shape of your `x`.

Try to find out at what place in your code is calling `inplace_abn_1.forward()`. It is not clear in ([link](https://github.com/mapillary/inplace_abn/issues/109#issue-428028165)). In the same link, you mentioned you are using `nn.parallel.parallel_apply`.  But, above, you mentioned that you are not using parallel training:
> @rotabulo Besides, I have not used the distributed training and I simply want to train my model with pytorch1.0~

Avoid using multi-gpu for now until you figure out where the error comes from.

Make sure that your entire model is running on the SAME device.  (see [this](https://discuss.pytorch.org/t/runtime-error-77/9392/9?u=sbelharbi))

Make sure that your batch size is ALWAYS `>=2`. As I remember, the code does not support a batch size of `1` (due to the bacthnorm). If you set your batch size to `2` and you have an odd number of samples, you will run to a batch with size `1`.

Does your code process at least one minibatch? or it raises the error at the first minibatch? does is run correctly on CPU?
