### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by LGYoung** [mapillary/inplace_abn#131]
File"~/anaconda3/envs/pytorch1.1/lib/python3.6/sitepackages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg  "Default process group is not initialized"
AssertionError: Default process group is not initialized
My env is:
Ubuntu 18.04
Cuda 10.0
Pytorch 1.1
GPU: 1 1080Ti and 1 1080
And I have tried run it on both 1 GPU and 2 GPUs but got the same problem.
Could u give me some help? Thx!

**Comment by ducksoup** [comment]
@LGYoung what is the exact command you are using to launch the training?

**Comment by scarftdd** [comment]
Hello, I have the same issue, my command is 
BatchNorm2d = functools.partial(InPlaceABNSync, activation='identity')
self.bn1 = BatchNorm2d(64)
then forward:
self.bn1(self.conv1(x))
the issue is:
  File "/home/ubuntu/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 588, in get_world_size
    return _get_group_size(group)
  File "/home/ubuntu/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 201, in _get_group_size
    _check_default_pg()
  File "/home/ubuntu/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 192, in _check_default_pg
    "Default process group is not initialized"

**Comment by ducksoup** [comment]
@scarftdd Maybe there's been a misunderstanding, I didn't mean to ask what is the Python code being used. I'm interested to know _how_ the code is run: directly from the Python interpreter vs. ipython vs. a script launched with `python script.py` etc.

This is relevant because of the way Pytorch distributed execution, which `InPlaceABNSync` uses, works. For an in-depth explanation refer to: https://pytorch.org/docs/stable/distributed.html

**Comment by scarftdd** [comment]
I use python3.6 version, a script launch

**Comment by ducksoup** [comment]
@scarftdd scripts using `InPlaceABNSync`, same as any other Pytorch script involving distributed functionality, must include multiprocessing initialization logic as described [here](https://pytorch.org/docs/stable/distributed.html#initialization), and possibly be launched using the pytorch distributed launch utility (_i.e._ `python -m torch.distributed.launch [torch.distributed.launch params] your_script.py [your_script params]`). The errors you and @LGYoung are seeing are due to the fact that you are not doing this.

Please refer to Pytorch's documentation and tutorials (_e.g._ [this one](https://pytorch.org/tutorials/intermediate/dist_tuto.html)) for an in-depth explanation.

**Comment by LetsGoFir** [comment]
> @scarftdd scripts using `InPlaceABNSync`, same as any other Pytorch script involving distributed functionality, must include multiprocessing initialization logic as described [here](https://pytorch.org/docs/stable/distributed.html#initialization), and possibly be launched using the pytorch distributed launch utility (_i.e._ `python -m torch.distributed.launch [torch.distributed.launch params] your_script.py [your_script params]`). The errors you and @LGYoung are seeing are due to the fact that you are not doing this.
> 
> Please refer to Pytorch's documentation and tutorials (_e.g._ [this one](https://pytorch.org/tutorials/intermediate/dist_tuto.html)) for an in-depth explanation.

Hi, can you tell me how to evaluate the model with InPlaceABNSync  trained with distributed  data parallel on single gpu?
