### ISSUE TITLE
Pre-trained network with BN => InplaceABN

### ISSUE THREAD

**Issue by ternaus** [mapillary/inplace_abn#179]
What is the process to replace BN layers with InplaceABN in a pre-trained network, say

`resnet34` from torchvision

?

**Comment by somedadaism** [comment]
Note that the Readme states that in this case you must expect a severe drop in performance,
because the scaling parameter is handled differently. In some sense I think the process you are searching for is: Adapt this code to use the scaling factor exactly as the regular BN and then replace your layers with inplace layers and copy the weights. Thats a lot of work though.

**Comment by ducksoup** [comment]
As @somedadaism said, porting weights from standard BN to InPlaceABN is a somehow cumbersome process, due to the different way the scaling parameters are handled. In general we recommend to use one of our pre-trained models, or if possible redo ImageNet training with the desired model and InPlaceABN.
