### ISSUE TITLE
memory leakage in inplace_abn_sync

### ISSUE THREAD

**Issue by lfz** [mapillary/inplace_abn#44]
Hi, thank you very much for this wonderful work!

But during using, I found that the memory usage is increasing during training, and then become stable  after reaching some certain point.

For example, the net using inplace_abn would cost 7 GB, but when using inplace_abn_sync, it would start with 7 GB and steadily increase the memory cost to around 11GB, and then become stable.

I used this module in a custom 3d CNN, is there anything special to watch or is this a potential bug? Thank you~

**Comment by lfz** [comment]
btw I use 8 cards, I found that the more cards I use, the more extra leakage would be caused.

When the card memory was fully filled, it would stuck and nothing will goes on until I kill it.

**Comment by rotabulo** [comment]
@lfz what happens in the 8 gpu case if you use non sync inplace ABN?

**Comment by lfz** [comment]
It goes quite normal, costing 7 GB on each card
I used this module in a docker environment
driver version 384.130
cuda 8.0
anaconda3
gcc & g++ 5.4
pytorch 0.4.1

have you seen this situation before?

**Comment by rotabulo** [comment]
@lfz how are you checking the memory consumption? Using `nvidia-smi` is not reliable because PyTorch implements a caching mechanisms that does not deallocate gpu memory unless strictly needed (e.g. if out-of-memory errors start to popup). We had issues training with sync inplace-ABN on a DGX with docker and 8 gpus, but since we had access only for limited time we could not properly debug the issue. What happens if you use less Gpus?

**Comment by lfz** [comment]
I monitor the memory with `nvidia-smi`. I tried to use `torch.cuda.empty_cache()` after each iteration, and the memory usage is still going up.

Now I am using 6 GPU and the leakage memory become smaller, the extra cost is about 1GB

Do you notice the extra memory cost when you use multiple gpus?

Where should I start to look at? do you have any suggestion?

**Comment by rotabulo** [comment]
@lfz we always trained models with 4 Gpus and we could replace inplace ABN with sync inplace ABN without issues. Technically, the sync inplace ABN will use a little bit of more memory, because it will move statistics to gpu 0, but those typically weight much less than the rest of the buffers. At some point we suspected that the issue you are referring to could have been due to docker, but we had no sudo rights on the machine to try a training outside of docker. Do you have this possibility?

**Comment by lfz** [comment]
I'll give it a try. Thank you for the quick response~

**Comment by lfz** [comment]
Hi, I have tried the testing outside the docker. and no luck : (

it behaves the same

**Comment by rotabulo** [comment]
@lfz since we have no 8 GPUs machines, we cannot reproduce the issue and debug it. As soon as we get one, we will check the issue. If you have new insights in the meanwhile, please let us know.

**Comment by ycszen** [comment]
@lfz Have you solved this problem? Recently I have the same issue, meanwhile, my experiment with inplace sync bn has a very slow training speed.

**Comment by rotabulo** [comment]
@ycszen we have released a new version of our code that requires PyTorch v1.0 and supports multi-process synchronization. This solves issues when training with more than 4 GPUs.
