### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by VanitarNordic** [mapillary/inplace_abn#50]
Hi,

How can I fine tune the model on a custom dataset which initially might have different number of classes?

You have provided the weights, but I could not find instructions for fine tuning.

I'll so appreciate if you explain a bit. Thanks.

**Comment by ducksoup** [comment]
Unfortunately our repo doesn't contain any pre-made code for fine-tuning on different datasets.
However, adapting the `train_imagenet.py` script to train on other similarly formatted image classification datasets should be quite straightforward. In a nutshell, the main modifications you need to make are:

1. Modify lines 82-92 to only load the model check-point and not the optimizer check-point: when you fine-tune you want the training process to restart from scratch.
2. Before passing the model checkpoint to `load_state_dict()` (line 87) manually delete any saved weights belonging to the pre-trained classifier.
3. Specify the option `strict=False` in `load_state_dict()` so that Pytorch doesn't complain that the loaded model doesn't contain weights for the classifier.
4. Modify the configuration file specifying the correct number of classes for your problem.
5. Launch the training with the `--resume` parameter to load the pre-trained model.

**Comment by sunggukcha** [comment]
@ducksoup 
 I really thanks to your kind comments.
 I am so newb that I do not know what to do with your (2) comment. What do you mean about the saved "weights"? Is that relevant to cache? How can I delete them?

**Comment by rotabulo** [comment]
I am closing the issue.
